### ISSUE TITLE
problem when running

### ISSUE THREAD

**Issue by thiagogomesverissimo** [wgnann/gsuite-groups#3]
@wgnann, 

I did the setup as described in readme, but I did not figure out why it is not working. Something related to method parser.add_subparsers.

```
python3 listas.py subscribe sites.fflch@ime.usp.br
Traceback (most recent call last):
  File "listas.py", line 130, in <module>
    main()
  File "listas.py", line 89, in main
    subparsers = parser.add_subparsers(title="command", dest="command", required=True)
  File "/usr/lib/python3.5/argparse.py", line 1708, in add_subparsers
    action = parsers_class(option_strings=[], **kwargs)
TypeError: __init__() got an unexpected keyword argument 'required'
```

**Comment by thiagogomesverissimo** [comment]
Done. We must use python3.7
